### ISSUE TITLE
requirements.dev.txt went wrong

### ISSUE THREAD

**Issue by lingxian55** [nftscan2022/nftscan-api-python-sdk#1]
![image](https://user-images.githubusercontent.com/33617805/161483547-4bb9e5f2-5d6b-4b86-a9bc-30a7d4a70e78.png)
there should have two equal signs
when i using pip -r ./requirements.dev.txt ,there are in error

**Comment by aausch** [comment]
https://github.com/nftscan2022/nftscan-api-python-sdk/commit/2dcd93581ddb9e0c7a043fcf7fd04adb2001e573
